### ISSUE TITLE
A bug was found. 

### ISSUE THREAD

**Issue by lpflhh** [icza/screp#65] opened 2024-12-07 21:29 UTC
A bug was found. If player A demolishes all of player B's buildings, the screp on player B's computer will show that player B's team has won, and player A's screp will show a draw, that is, WinnerTeam=0.
[LastReplay.zip](https://github.com/user-attachments/files/18049919/LastReplay.zip)

**Comment by icza** [comment] 2024-12-07 21:52
This is a duplicate of #32.

Winner is not stored in the replay. I implemented some algorithms to detect the winner, but the stored info in replays is insufficient and this algorithm cannot be 100% accurate.

**Closed** 2024-12-17 12:09 UTC
